# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 800f8d3286ecc5430fa4ff78cbee521831b34054634e19dc6ab221f7ec6ca1d1fd16e2caeed96bbf1c945b91ef978af38f3aecc35d31a4ae9fbd37670aa64983

test:
  secret_key_base: 976f3813e10dd2d2ecdc0b20e9d5f441ec37c9b88798eaddbead5b5506b17318867c517b8f83573a294fae8e0850b96f5229d4d0cbb0368c6519a57dbba3e6c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
